global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888', 'otel-collector:8889']
    scrape_interval: 10s

  - job_name: 'spring-boot-backend'
    static_configs:
      - targets: ['looper-backend:8080']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s

  # - job_name: 'fastapi-ai-service'
  #   static_configs:
  #     - targets: ['looper-ai:8000']
  #   metrics_path: '/metrics'
  #   scrape_interval: 15s

  - job_name: 'jaeger'
    static_configs:
      - targets: ['jaeger:14269']
    scrape_interval: 15s