server:
  http_listen_port: 3200
  log_level: info

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318

ingester:
  max_block_bytes: 1_000_000
  complete_block_timeout: 15m

compactor:
  compaction:
    compaction_window: 1h
    max_compaction_objects: 1000000
    block_retention: 336h  # 14일
    compacted_block_retention: 1h

storage:
  trace:
    backend: local
    local:
      path: /var/tempo/blocks
    wal:
      path: /var/tempo/wal
    pool:
      max_workers: 100
      queue_depth: 10000

querier:
  max_concurrent_queries: 20
  search:
    query_timeout: 5m
  trace_by_id:
    query_timeout: 1m

query_frontend:
  max_retries: 2
  search:
    concurrent_jobs: 1000
    target_bytes_per_job: 104857600  # 100MB

metrics_generator:
  registry:
    external_labels:
      source: tempo
      cluster: docker-compose
  storage:
    path: /var/tempo/generator/wal
    remote_write:
      - url: http://prometheus:9090/api/v1/write
        send_exemplars: true
  processor:
    service_graphs:
      dimensions:
        - db.system
        - db.operation
        - db.name
    span_metrics:
      dimensions:
        - service.name
        - span.kind
        - status.code
        - db.system
        - db.operation
        - db.name
        - db.sql.table
      histogram_buckets: [0.001, 0.002, 0.005, 0.01, 0.02, 0.05, 0.1, 0.2, 0.5, 1, 2, 5]
overrides:
  defaults:
    metrics_generator:
      processors: [service-graphs, span-metrics]
      max_active_series: 100000
    ingestion:
      rate_limit_bytes: 50_000_000
      burst_size_bytes: 50_000_000
      max_traces_per_user: 100000