apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    jsonData:
      httpMethod: POST
      exemplarTraceIdDestinations:
        - datasourceUid: tempo
          name: trace_id
          urlDisplayLabel: 'View in Tempo'
    isDefault: true
    editable: true
    uid: prometheus 

  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686
    editable: true
    uid: jaeger  

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: true
    uid: loki 

  - name: OpenTelemetry
    type: prometheus
    access: proxy
    url: http://otel-collector:8889
    editable: true
    uid: opentelemetry  

  - name: Tempo
    type: tempo
    access: proxy
    orgId: 1
    url: http://tempo:3200
    basicAuth: false
    isDefault: false
    version: 1
    editable: true
    uid: tempo
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: prometheus
      search:
        hide: false
      nodeGraph:
        enabled: true
      lokiSearch:
        datasourceUid: loki
      traceQuery:
        timeShiftEnabled: true
        spanStartTimeShift: '-1h'
        spanEndTimeShift: '1h'
      tracesToLogs:
        datasourceUid: loki
        mapTagNamesEnabled: true
        mappedTags:
          - key: service.name
            value: service
          - key: db.name
            value: database
          - key: db.system
            value: db_system
        filterByTraceID: true
        filterBySpanID: true
        spanStartTimeShift: '-1h'
        spanEndTimeShift: '1h'
      tracesToMetrics:
        datasourceUid: prometheus
        tags:
          - key: service.name
            value: service
          - key: db.operation
            value: operation
          - key: db.name
            value: database
        queries:
          - name: 'Database Query Rate'
            query: 'sum(rate(db_client_operation_duration_count{$$__tags}[5m]))'
          - name: 'Database Query Latency P95'
            query: 'histogram_quantile(0.95, sum(rate(db_client_operation_duration_bucket{$$__tags}[5m])) by (le))'
          - name: 'Database Errors'
            query: 'sum(rate(db_client_operation_errors_total{$$__tags}[5m]))'
      tracesToProfiles:
        datasourceUid: ''
        tags: []
      exemplarTraceIdDestinations:
        - datasourceUid: tempo
          name: trace_id